#
# The variables for the conference
#
# TODO : we want to manage this in the DB eventually so that we can have many conferences
#

development:
    :conference:
        :name: MyConvention
        :email: help@help.com
        :start_date: "2013-08-29 00:00:00"
        :number_of_days: 5
        :manifest: /Users/balen/cache.manifest
    
production:
    :conference:
        :name: MyConvention
        :email: help@help.com
        :start_date: 2013-02-15 00:00:00
        :number_of_days: 3

test:
    :conference:
        :name: MyConvention
        :email: help@help.com
        :start_date: 2013-02-15 00:00:00
        :number_of_days: 3
