---
  - name: Assures /www/sac/shared/config dir exists
    file: path=/www/sac/shared/config state=directory
  - name: Set database.yml
    template:
      src: database.yml.j2
      dest: /www/sac/shared/config/database.yml
  - name: Install Postgresql
    apt: "pkg={{ item }} state=installed update_cache=yes"
    with_items:
      - postgresql
      - postgresql-contrib
      - libpq-dev
      - python-psycopg2